import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { getServerSession } from 'next-auth';
import SessionProvider from '../components/providers/SessionProvider';
import { AUTH_OPTIONS } from './api/auth/[...nextauth]/options';
import { Nav } from '@/components/shell/nav';
import { Footer } from '@/components/shell/footer';
import ToastProvider from '@/components/providers/ToastProvider';
import TawkToProvider from '@/components/providers/TawkProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(AUTH_OPTIONS);
  return (
    <html lang="en">
      <body className={`flex flex-col min-h-screen ${inter.className}`}>
        <SessionProvider session={session}>
          <TawkToProvider>
            <ToastProvider>
            <main className="flex-1">
              <Nav />
              {children}
            </main>
          </ToastProvider>
          </TawkToProvider>
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
