import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { getServerSession } from 'next-auth';
import SessionProvider from '../components/SessionProvider';
import { AUTH_OPTIONS } from './api/auth/[...nextauth]/options';
import { Nav } from '@/components/nav';
import { Footer } from '@/components/footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(AUTH_OPTIONS);
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <SessionProvider session={session}>
          <main className="flex-1">
            <Nav />
            {children}
          </main>
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
