import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { getServerSession } from 'next-auth';
import SessionProvider from '../components/SessionProvider';
import { AUTH_OPTIONS } from './api/auth/[...nextauth]/options';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(AUTH_OPTIONS);
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          <main className="p-4">
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
